import {useEffect,useState,type ComponentType} from 'react';
import {createRoot} from 'react-dom/client';
import {HermesMotionProvider} from '../src/lib/motion';
import {LoadingDemo,ScreenDemo} from './loading';
import {ThinkingDemo,StreamingDemo,ToolsDemo,TasksDemo,ChatDemo} from './conversation';
import {DecisionDemo,PromptDemo,NavigationDemo,SearchDemo,SelectionDemo,InspectorDemo} from './controls';
import {RecommendationDemo,ContextDemo,DiffDemo,RecordsDemo,FilterDemo,FlowDemo,InsightsDemo,CodeDemo} from './data';
type Entry={id:string;name:string;group:string;icon:string;component:ComponentType;exportName:string;use:string;motion:string;props?:string;};
const entries:Entry[]=[
 {id:'loading-state',name:'Loading',group:'Conversation',icon:'iris',component:LoadingDemo,exportName:'LoadingState',use:'Show activity without inventing progress.',motion:'650ms wave · 950ms orbit · 1.4s shimmer',props:'label="Reviewing criteria" variant="Orbit"'},
 {id:'thinking-state',name:'Thinking',group:'Conversation',icon:'trace',component:ThinkingDemo,exportName:'ThinkingState',use:'Expose work summaries as Iris progresses.',motion:'5.8s sequence · 400ms disclosure'},
 {id:'streaming-text',name:'Streaming response',group:'Conversation',icon:'context',component:StreamingDemo,exportName:'StreamingText',use:'Keep sources and follow-ups attached to the response.',motion:'Progressive text · staggered source reveal'},
 {id:'tool-chips',name:'Tool activity',group:'Conversation',icon:'settings',component:ToolsDemo,exportName:'ToolChips',use:'Make tool calls inspectable without filling the conversation.',motion:'700ms steps · expandable tool details'},
 {id:'task-rows',name:'Task progress',group:'Conversation',icon:'loop',component:TasksDemo,exportName:'TaskRows',use:'Separate running, blocked, failed, and completed work.',motion:'5.3s sequence · capsules and list'},
 {id:'chat-composer',name:'Chat',group:'Conversation',icon:'iris',component:ChatDemo,exportName:'ChatComposer',use:'Keep independent sessions and their work together.',motion:'3.1s reply sequence · tab transitions'},
 {id:'prompt-bar',name:'Prompt bar',group:'Interaction',icon:'iris',component:PromptDemo,exportName:'PromptBar',use:'Compose with context, commands, model and runtime.',motion:'180ms menus · 220ms glide · submit sweep'},
 {id:'approval-card',name:'Decision prompt',group:'Interaction',icon:'admission',component:DecisionDemo,exportName:'ApprovalCard',use:'Collect direction before Iris starts. No business approval is implied.',motion:'360ms question change · 480ms auto-advance'},
 {id:'sidebar-nav',name:'Navigation',group:'Interaction',icon:'session-history',component:NavigationDemo,exportName:'SidebarNav',use:'Move between workspaces and sessions without losing your place.',motion:'280ms collapse · 180ms search reveal'},
 {id:'search',name:'Search',group:'Interaction',icon:'search',component:SearchDemo,exportName:'SearchList',use:'Find a workflow or use a suggested prompt.',motion:'Live filtering · 220ms menu highlight'},
 {id:'selection-actions',name:'Selection actions',group:'Interaction',icon:'context',component:SelectionDemo,exportName:'SelectionActions',use:'Revise selected text and keep or discard the result.',motion:'320ms toolbar · 400ms expansion · streamed edit'},
 {id:'fine-tune-card',name:'Inspector',group:'Interaction',icon:'settings',component:InspectorDemo,exportName:'FineTuneCard',use:'Adjust the artifact with immediate visual feedback.',motion:'Live property changes · gliding option menus'},
 {id:'recommendation-card',name:'Recommendation',group:'Context & decisions',icon:'skill',component:RecommendationDemo,exportName:'RecommendationCard',use:'Show the proposal, evidence, and the next human action.',motion:'Meter reveal · alternatives disclosure'},
 {id:'context-cards',name:'Source cards',group:'Context & decisions',icon:'context',component:ContextDemo,exportName:'ContextCards',use:'Keep retrieved evidence inspectable and attributable.',motion:'Staggered source cards'},
 {id:'diff-table',name:'Proposed changes',group:'Context & decisions',icon:'add-to-collective',component:DiffDemo,exportName:'DiffTable',use:'Review exactly what changes before applying it.',motion:'Row sweep · selective accept and reject'},
 {id:'records-table',name:'Records',group:'Data & workspace',icon:'people',component:RecordsDemo,exportName:'RecordsTable',use:'Inspect, filter, select, sort, and resize partner records.',motion:'Row hover · menus · column resizing'},
 {id:'filter-table',name:'Status filters',group:'Data & workspace',icon:'inbox',component:FilterDemo,exportName:'FilterTable',use:'Focus on the work that needs attention.',motion:'Filter transitions · reorganized rows'},
 {id:'flowchart',name:'Workflow',group:'Data & workspace',icon:'loop',component:FlowDemo,exportName:'Flowchart',use:'Define a repeatable trigger and human review boundary.',motion:'Node entrance · condition menus'},
 {id:'insight-cards',name:'Insights',group:'Data & workspace',icon:'trace',component:InsightsDemo,exportName:'InsightCards',use:'Compare activity and inspect the underlying values.',motion:'Paged insights · interactive chart scrub'},
 {id:'code-block',name:'Code & diff',group:'Data & workspace',icon:'skill',component:CodeDemo,exportName:'CodeBlock',use:'Inspect the skill implementation and proposed edits.',motion:'Listing and diff transitions'},
 {id:'agent-screen',name:'Agent screen',group:'Data & workspace',icon:'cloud',component:ScreenDemo,exportName:'AgentScreen',use:'Open the workspace and demonstrate a repeatable loop.',motion:'1.55s signal · 3.2s orbit · 240ms viewer'},
];
const fallback='loading-state';
function App(){
 const[selected,select]=useState(()=>entries.some(x=>x.id===location.hash.slice(1))?location.hash.slice(1):fallback);
 const[mode,setMode]=useState<'preview'|'usage'>('preview');const[replay,setReplay]=useState(0);const[reduce,setReduce]=useState(false);const[copied,setCopied]=useState(false);const[notice,setNotice]=useState('');
 useEffect(()=>{const fn=()=>select(entries.some(x=>x.id===location.hash.slice(1))?location.hash.slice(1):fallback);window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});setReplay(0);setMode('preview');setCopied(false)},[selected]);
 useEffect(()=>{if(!copied&&!notice)return;const id=setTimeout(()=>{setCopied(false);setNotice('')},2000);return()=>clearTimeout(id)},[copied,notice]);
 const current=entries.find(x=>x.id===selected)!;const Specimen=current.component;
 const code=`import { HermesMotionProvider, ${current.exportName} } from '@hermes/motion-components';\nimport '@hermes/motion-components/styles.css';\n\n<HermesMotionProvider>\n  <${current.exportName}${current.props?' '+current.props:''} />\n</HermesMotionProvider>`;
 const copy=async()=>{try{await navigator.clipboard.writeText(code);setCopied(true)}catch{setNotice('Copy unavailable. Select the code to copy.')}};
 return <HermesMotionProvider reducedMotion={reduce}><div className="library-shell"><aside className="library-nav"><a className="library-brand" href="#loading-state"><img src="assets/iris.svg" alt=""/>Hermes</a><div className="library-label">Component library <span>21</span></div><nav aria-label="Components">{[...new Set(entries.map(x=>x.group))].map(group=><div className="nav-group" key={group}><p>{group}</p>{entries.filter(x=>x.group===group).map(x=><a key={x.id} href={'#'+x.id} aria-current={selected===x.id?'page':undefined}><img src={'assets/'+x.icon+'.svg'} alt=""/>{x.name}</a>)}</div>)}</nav><footer><span className="library-dot"/>Hermes Enterprise</footer></aside><main className="library-main"><header className="library-top"><span>Design system <span className="slash">/</span> Motion</span><label className="motion-toggle"><input type="checkbox" checked={reduce} onChange={e=>setReduce(e.target.checked)}/><span aria-hidden className="switch-track"/>Reduce motion</label></header><div className="library-body"><div className="component-heading"><div><p>{current.group}</p><h1>{current.name}</h1></div><a className="reference-link" href={'https://www.beautifului.dev/#'+current.id} target="_blank" rel="noreferrer">Reference ↗</a></div><div className="stage-toolbar"><div className="view-tabs" role="tablist" aria-label="Component view"><button role="tab" id="preview-tab" aria-controls="preview-panel" aria-selected={mode==='preview'} onClick={()=>setMode('preview')}>Preview</button><button role="tab" id="usage-tab" aria-controls="usage-panel" aria-selected={mode==='usage'} onClick={()=>setMode('usage')}>Usage</button></div>{mode==='preview'?<button className="replay" onClick={()=>setReplay(x=>x+1)}><span>↻</span>Replay</button>:<button className="replay" onClick={copy}>{copied?'Copied ✓':'Copy import'}</button>}</div>{mode==='preview'?<section id="preview-panel" role="tabpanel" aria-labelledby="preview-tab" className={'component-stage stage-'+selected}><div className="specimen-context"><img src="assets/iris.svg" alt=""/><span>Iris</span><span className="specimen-data">Example data</span></div><div className="specimen-content"><Specimen key={`${selected}-${replay}-${reduce}`}/></div></section>:<section role="tabpanel" id="usage-panel" aria-labelledby="usage-tab" className="usage-panel"><pre><code>{code}</code></pre><p>Use props and callbacks to connect real data. The gallery’s demonstrations run locally.</p></section>}<div className="component-notes"><p>{current.use}</p><span>{current.motion}</span></div><div className="library-bottom"><span>Inter · Barlow Condensed · Hermes glass</span><a href="https://www.beautifului.dev/license" target="_blank" rel="noreferrer">Adapted from Beautiful UI · MIT</a></div></div></main>{notice&&<div role="status" className="library-toast">{notice}</div>}</div></HermesMotionProvider>;
}
createRoot(document.getElementById('root')!).render(<App/>);
